/**
 * PCG/ADV(EX 시리즈) 트레이너 JP→EN 이름 사전 (merge-en-identity 트레이너 매칭용).
 *
 * ⚠⚠ 이 시대 JP 데이터는 **원어 미보유**: jp-tcg-PCG* 의 명칭·attacks 는 EN(ptcg.io/tcgdex)의
 * 기계번역 대체물이다(예: 山ムーン=Mt. Moon 직역, 素晴らしいボール=Great Ball 직역 — 정식명 スーパーボール 아님).
 * pc-jp 카드DB는 cardID ~3000(DP 시대)부터만 존재해 PCG 원어 교정 불가(2026-06-06 탐침 확정).
 * 따라서 본 사전의 JP 키는 "DB에 실재하는 기계번역명 verbatim"이며, 정식 일본어명이 아니다.
 * 추후 진짜 JP 소스 확보·재수집 시 이 항목들은 자연 미발화되고 정식명으로 재등재하면 된다.
 * EN 값은 ptcg.io(set.id:ex6/ex7/ex8/ex10) name verbatim. 배치마다 orphan 대조검증 후 추가.
 */
export const TR_JP2EN: Record<string, string> = {
  // ── PCG1 전설의 비상(en-tcg-ex6 EX FireRed & LeafGreen, 2026-06-06 orphan 대조검증) ──
  "素晴らしいボール": "Great Ball",
  "VSシーカー": "VS Seeker",
  "pokedex Handy909": "PokéDex HANDY909",
  "オーク教授の研究": "Prof. Oak's Research",
  "セリオのネットワーク": "Celio's Network",
  "ビルのメンテナンス": "Bill's Maintenance",
  "exp。共有": "EXP.ALL",
  "山ムーン": "Mt. Moon",
  // ── PCG2 창공의 격돌(en-tcg-ex8 EX Deoxys) ──
  "コズモ教授の発見": "Professor Cozmo's Discovery",
  "クリスタルシャード": "Crystal Shard",
  "宇宙センター": "Space Center",
  "流星滝": "Meteor Falls",
  "スクランブルエネルギー": "Scramble Energy",
  "エネルギーを癒します": "Heal Energy",
  "エネルギーを高めます": "Boost Energy",
  // ── PCG3 로켓단의 역습(en-tcg-ex7 EX Team Rocket Returns) ──
  "捕虜！ハンドエクステンション": "Pow! Hand Extension",
  "急降下！テレポーター": "Swoop! Teleporter",
  "驚き！  タイムマシン": "Surprise! Time Machine",
  "ベンチャー爆弾": "Venture Bomb",
  "ポケモンレトリバー": "Pokémon Retriever",
  "模倣": "Copycat",
  "ロケットの管理者。": "Rocket's Admin.",
  "ロケットの使命": "Rocket's Mission",
  "ロケットの隠れ家": "Rocket's Hideout",
  "ロケットのトリッキーなジム": "Rocket's Tricky Gym",
  "rエネルギー": "R Energy",
  "ダークメタルエネルギー": "Dark Metal Energy",
  "これがチームロケットが来ます！": "Here Comes Team Rocket!",
  // ── PCG4 금빛 하늘, 은빛 바다(en-tcg-ex10 EX Unseen Forces) ──
  "エルム教授のトレーニング方法": "Professor Elm's Training Method",
  "メアリーの要求": "Mary's Request",
  "堅実な怒り": "Solid Rage",
  "シトラスベリー": "Sitrus Berry",
  "エネルギー根": "Energy Root",
  "呪いパウダー": "Curse Powder",
  "ふわふわベリー": "Fluffy Berry",
  "保護オーブ": "Protective Orb",
  "サイクロンエネルギー": "Cyclone Energy",
  "ワープエネルギー": "Warp Energy",
  // ── PCG5 환상의 숲(en-tcg-ex12 EX Legend Maker, 2026-06-06 orphan 대조검증) ──
  "爪の化石": "Claw Fossil",
  "神秘的な化石": "Mysterious Fossil",
  "根の化石": "Root Fossil",
  "フィールドワーカー": "Fieldworker",
  "奇妙な洞窟": "Strange Cave",
  "フルフレーム": "Full Flame",
  "巨大な切り株": "Giant Stump",
  "呪われた石": "Cursed Stone",
  "パワーツリー": "Power Tree",
  "エネルギーを反応させます": "React Energy",
  // ── PCG6 호론의 연구탑(en-tcg-ex11 EX Delta Species) ──
  "ホロントランシーバー": "Holon Transceiver",
  "ホロン科学者": "Holon Scientist",
  "ホロン研究者": "Holon Researcher",
  "ホロンメンター": "Holon Mentor",
  "ホロン農家": "Holon Farmer",
  "ホロン・ラス": "Holon Lass",
  "ホロン研究塔": "Holon Research Tower",
  "ホロン遺跡": "Holon Ruins",
  "ホロンエネルギーGL": "Holon Energy GL",
  "ホロンエネルギーff": "Holon Energy FF",
  "ホロンエネルギーwp": "Holon Energy WP",
  // ── PCG7 호론의 환영(en-tcg-ex13 EX Holon Phantoms) ──
  "珍しいキャンディー": "Rare Candy",
  "ホロン化石": "Holon Fossil",
  "ホロンアドベンチャー": "Holon Adventurer",
  "ホロン湖": "Holon Lake",
  "デルタレインボーエネルギー": "δ Rainbow Energy",
  // ── PCG8 기적의 결정(en-tcg-ex14 EX Crystal Guardians) ──
  "暴風": "Windstorm",
  "キャスト・アウェイ": "Castaway",
  "メモリベリー": "Memory Berry",
  "神秘的なシャード": "Mysterious Shard",
  "停止クリスタル": "Cessation Crystal",
  "クリスタルビーチ": "Crystal Beach",
  "ホロンサークル": "Holon Circle",
  "二重虹のエネルギー": "Double Rainbow Energy",
  // ── PCG9 끝자락의 공방(en-tcg-ex15 EX Dragon Frontiers) ──
  "古い棒": "Old Rod",
  "島の隠者": "Island Hermit",
  "強さの魅力": "Strength Charm",
  "ホロンの遺産": "Holon Legacy",
  // ── PCG10 월드챔피언스팩(en-tcg-ex16 EX Power Keepers, 2026-06-06) ──
  // ⚠ PCG10 JP 데이터는 번역조차 없는 EN raw — JP 키 = EN명 identity(supertype null 백필과 세트)
  "Energy Recycle System": "Energy Recycle System",
  "Energy Switch": "Energy Switch",
  "Energy Removal 2": "Energy Removal 2",
  "Great Ball": "Great Ball",
  "Master Ball": "Master Ball",
  "Claw Fossil": "Claw Fossil",
  "Mysterious Fossil": "Mysterious Fossil",
  "Root Fossil": "Root Fossil",
  "Scott": "Scott",
  "Professor Birch": "Professor Birch",
  "Steven's Advice": "Steven's Advice",
  "Battle Frontier": "Battle Frontier",
  "Sidney's Stadium": "Sidney's Stadium",
  "Drake's Stadium": "Drake's Stadium",
  "Phoebe's Stadium": "Phoebe's Stadium",
  "Glacia's Stadium": "Glacia's Stadium",
  // ── ADV1~5(en-tcg-ex1~5, 2026-06-06) — ADV 시대 전체가 무번역 EN raw(PCG10 동형) → identity 키 ──
  "PokeNav": "PokéNav",
  "Lady Outing": "Lady Outing",
  "Oran Berry": "Oran Berry",
  "Double Full Heal": "Double Full Heal",
  "Rare Candy": "Rare Candy", // ADV raw 키(영문) — PCG7 일본어 키 珍しいキャンディー와 별개. Professor Birch/화석류 등은 PCG10 identity 키 재사용
  "Lanette's Net Search": "Lanette's Net Search",
  "Wally's Training": "Wally's Training",
  "TV Reporter": "TV Reporter",
  "Mr. Briney's Compassion": "Mr. Briney's Compassion",
  "Balloon Berry": "Balloon Berry",
  "Buffer Piece": "Buffer Piece",
  "Dual Ball": "Dual Ball",
  "Warp Point": "Warp Point",
  "Team Magma Belt": "Team Magma Belt",
  "Team Aqua Belt": "Team Aqua Belt",
  "Team Magma Schemer": "Team Magma Schemer",
  "Team Aqua Schemer": "Team Aqua Schemer",
  "Maxie": "Maxie",
  "Archie": "Archie",
  "Team Magma Technical Machine 01": "Team Magma Technical Machine 01",
  "Team Aqua Technical Machine 01": "Team Aqua Technical Machine 01",
  "Strength Charm": "Strength Charm",
  // ── e-Card E1~E5(en-tcg-ecard1~3, 2026-06-06) — 기계번역 직역(orphan 대조검증). 기존 키 재사용: エルム教授/オーク教授/強さの魅力/ビルのメンテナンス/模倣/メモリベリー/クリスタルシャード ──
  "エネルギー回復": "Energy Restore",
  "エネルギー電荷": "Power Charge",
  "エネルギー除去2": "Energy Removal 2",
  "メアリーの衝動": "Mary's Impulse",
  "スーパースクープアップ": "Super Scoop Up",
  "デュアルボール": "Dual Ball",
  "ポケモンナース": "Pokémon Nurse",
  "ポケモン反転": "Pokémon Reversal",
  "マスターボール": "Master Ball",
  "マルチテクニカルマシン01": "Multi Technical Machine 01",
  "ワープポイント": "Warp Point",
  "脱力感ガード": "Weakness Guard",
  "スーパーエネルギー除去2": "Super Energy Removal 2",
  "先見者": "Seer",
  "ポケモンファンクラブ": "Pokémon Fan Club",
  "町のボランティア": "Town Volunteers",
  "グラスキューブ01": "Grass Cube 01",
  "ファイアキューブ01": "Fire Cube 01",
  "ウォーターキューブ01": "Water Cube 01",
  "ライトニングキューブ01": "Lightning Cube 01",
  "サイキックキューブ01": "Psychic Cube 01",
  "戦いキューブ01": "Fighting Cube 01",
  "闇キューブ01": "Darkness Cube 01",
  "金属キューブ01": "Metal Cube 01",
  "ポケモンパーク": "Pokémon Park",
  "発電所": "Power Plant",
  "エネルギースイッチ": "Energy Switch",
  "旅行セールスマン": "Traveling Salesman",
  "ジャグラー": "Juggler",
  "森林保護者": "Forest Guardian",
  "癒しベリー": "Healing Berry",
  "タイムシャード": "Time Shard",
  "海底遺跡": "Undersea Ruins",
  "アプリコーンの森": "Apricorn Forest",
  "ハイパーポーション": "Hyper Potion",
  "砂漠のシャーマン": "Desert Shaman",
  "オラクル": "Oracle",
  "地下遠征": "Underground Expedition",
  "スターピース": "Star Piece",
  "ミステリープレートa": "Mystery Plate α",
  "ミステリープレートb": "Mystery Plate β",
  "ミステリープレートY": "Mystery Plate γ",
  "ミステリープレートo": "Mystery Plate δ",
  "地下湖": "Underground Lake",
  "ミラージュスタジアム": "Mirage Stadium",
  "高速ボール": "Fast Ball",
  "友達のボール": "Friend Ball",
  "ルアーボール": "Lure Ball",
  "遺物ハンター": "Relic Hunter",
  "漁師": "Fisherman",
  "アプリコーンメーカー": "Apricorn Maker",
  "奇跡の球体a": "Miracle Sphere α",
  "奇跡の球体b": "Miracle Sphere β",
  "奇跡の球体y": "Miracle Sphere γ",
  "古代の遺跡": "Ancient Ruins",
  "ミステリーゾーン": "Mystery Zone",
  // ── NEO neo1~4(en-tcg-neo1~4, 2026-06-06) — 기계번역 직역. ⚠ エネルギー電荷 키는 e-Card에서 Power Charge로 선점(시대별 충돌) → neo1 Energy Charge는 수동 ──
  "ベリー": "Berry",
  "スーパーロッド": "Super Rod",
  "二重突風": "Double Gust",
  "ポケモンマーチ": "Pokémon March",
  "Moomooミルク": "Moo-Moo Milk",
  "エルム教授": "Professor Elm",
  "ゴールドベリー": "Gold Berry",
  "カードフリップゲーム": "Card-Flip Game",
  "ミラクルベリー": "Miracle Berry",
  "新しいpokedex": "New Pokédex",
  "ビルのテレポーター": "Bill's Teleporter",
  "スプラウトタワー": "Sprout Tower",
  "ecogym": "Ecogym",
  "フォーカスバンド": "Focus Band",
  "メアリー": "Mary",
  "アーケードゲーム": "Arcade Game",
  "タイムカプセル": "Time Capsule",
  "スーパーエネルギー検索": "Super Energy Retrieval",
  "ポクギア": "PokéGear",
  "エネルギーアーク": "Energy Ark",
  "化石卵": "Fossil Egg",
  "ハイパーデボルブスプレー": "Hyper Devolution Spray",
  "ヒーリングフィールド": "Healing Field",
  "ポケモンブリーダーフィールド": "Pokémon Breeder Fields",
  "粉末を癒します": "Heal Powder",
  "ビルからのメール": "Mail from Bill",
  "エネルギースタジアム": "Energy Stadium",
  "エネルギー増幅器": "Energy Amplifier",
  "反撃の爪": "Counterattack Claws",
  "拡大鏡": "Magnifier",
  "ポケモンパーソナリティテスト": "Pokémon Personality Test",
  "ラッキースタジアム": "Lucky Stadium",
  "チームロケットの邪悪な行為": "Team Rocket's Evil Deeds",
  "思考ウェーブマシン": "Thought Wave Machine",
  "壊れた地上ジム": "Broken Ground Gym",
  "詐欺師オーク教授の発明": "Impostor Professor Oak's Invention",
  "ラジオタワー": "Radio Tower",
  // ── 구판 PMCG1~6(en-tcg-base1/2/3/5·gym1/gym2, 2026-06-06) — 기계번역 오역 다수(請求書=Bill·富士通り=Mr. Fuji·霧=Misty·中佐=Lt. Surge) ──
  "エネルギー除去": "Energy Removal",
  "ポーション": "Potion",
  "風の突風": "Gust of Wind",
  "スイッチ": "Switch",
  "請求書": "Bill",
  "スーパーポーション": "Super Potion",
  "エネルギー検索": "Energy Search",
  "オーク教授": "Professor Oak",
  "復活します": "Revive",
  "ディフェンダー": "Defender",
  "フルヒール": "Full Heal",
  "プラスパワー": "PlusPower",
  "pokedex": "Pokédex",
  "ポケモンセンター": "Pokémon Center",
  "ポケモンフルート": "Poké Flute",
  "メンテナンス": "Maintenance",
  "デボルブスプレー": "Devolution Spray",
  "アイテムファインダー": "Item Finder",
  "超エネルギー除去": "Super Energy Removal",
  "詐欺師オーク教授": "Impostor Professor Oak",
  "コンピューター検索": "Computer Search",
  "Clefairy Doll": "Clefairy Doll",
  "すくい上げます": "Scoop Up",
  "ポケモントレーダー": "Pokémon Trader",
  "ポケモンブリーダー": "Pokémon Breeder",
  "ラス": "Lass",
  "ポークボール": "Poké Ball",
  "ギャンブラー": "Gambler",
  "リサイクル": "Recycle",
  "富士通り": "Mr. Fuji",
  "寝る！": "Sleep!",
  "掘り": "Digger",
  "GOOPガス攻撃": "Goop Gas Attack",
  "毎晩のごみ走り": "Nightly Garbage Run",
  "チャレンジ！": "Challenge!",
  "詐欺師オークの復ven": "Imposter Oak's Revenge",
  "上司のやり方": "The Boss's Way",
  "ロケットのスニーク攻撃": "Rocket's Sneak Attack",
  "エネルギーの流れ": "Energy Flow",
  "ミスティの決闘": "Misty's Duel",
  "ミスティの涙": "Misty's Tears",
  "狭いジム": "Narrow Gym",
  "想起": "Recall",
  "エリカのメイド": "Erika's Maids",
  "エリカの香水": "Erika's Perfume",
  "慈善": "Charity",
  "ミスティの怒り": "Misty's Wrath",
  "バーミリオンシティジム": "Vermilion City Gym",
  "ブロックのトレーニング方法": "Brock's Training Method",
  "セラドンシティジム": "Celadon City Gym",
  "ピューターシティジム": "Pewter City Gym",
  "セルリアンシティジム": "Cerulean City Gym",
  "Surgeの条約": "Lt. Surge's Treaty",
  "良いマナー": "Good Manners",
  "エリカ": "Erika",
  "エリカの優しさ": "Erika's Kindness",
  "霧": "Misty",
  "ミスティの願い": "Misty's Wish",
  "カオスジム": "Chaos Gym",
  "秘密の使命": "Secret Mission",
  "ブロック": "Brock",
  "ブロックの保護": "Brock's Protection",
  "レジスタンスジム": "Resistance Gym",
  "中佐": "Lt. Surge",
  "Surgeの秘密計画中": "Lt. Surge's Secret Plan",
  "除去ジムはありません": "No Removal Gym",
  "ロケットのトレーニングジム": "Rocket's Training Gym",
  "ロケットのtrap": "Rocket's Trap",
  "ブレインのギャンブル": "Blaine's Gamble",
  "ゴミ交換": "Trash Exchange",
  "サブリナの視線": "Sabrina's Gaze",
  "透明な壁": "Transparent Walls",
  "ブレインの最後の手段": "Blaine's Last Resort",
  "ブレインのクイズ3": "Blaine's Quiz #3",
  "コガの忍者のトリック": "Koga's Ninja Trick",
  "くすぐるマシン": "Tickling Machine",
  "Cinnabar City Gym": "Cinnabar City Gym",
  "フクシアシティジム": "Fuchsia City Gym",
  "Sabrina's esp": "Sabrina's ESP",
  "サブリナのサイキックコントロール": "Sabrina's Psychic Control",
  "チームロケットのミニオン": "Team Rocket's Minion",
  "サフランシティジム": "Saffron City Gym",
  "ロケットの秘密の実験": "Rocket's Secret Experiment",
  "ロケットの地雷原ジム": "Rocket's Minefield Gym",
  "ブレイン": "Blaine",
  "コガ": "Koga",
  "ジョバンニ": "Giovanni",
  "ジョバンニの最後の手段": "Giovanni's Last Resort",
  "ビリディアンシティジム": "Viridian City Gym",
  "サブリナ": "Sabrina",
  "Life Herb": "Life Herb",
  "Ancient Technical Machine Ice": "Ancient Technical Machine [Ice]",
  "Ancient Technical Machine Rock": "Ancient Technical Machine [Rock]",
  "Ancient Technical Machine Steel": "Ancient Technical Machine [Steel]",
  "Island Cave": "Island Cave",
  "Ancient Tomb": "Ancient Tomb",
  "Desert Ruins": "Desert Ruins",
  "High Pressure System": "High Pressure System",
  "Low Pressure System": "Low Pressure System",
  "Magnetic Storm": "Magnetic Storm",
};
