/**
 * SWSH(소드·실드) 트레이너/스타디움 JP→EN 이름 사전 (merge-en-identity 트레이너 매칭용).
 * 일러스트레이터는 같은 일러에 여러 카드가 섞여 스크램블되므로, 트레이너의 정체성은 *이름*으로 잡는다.
 * EN명은 pokemontcg.io(set.id:swsh1 등) 의 name 문자열을 verbatim 으로 사용(버킷 일치 필수).
 * JP명은 jp-tcg-S1W·S1H 등 DB JP 로케일명, 일러스트레이터 매칭으로 정렬. 배치마다 추가.
 */
export const TR_JP2EN: Record<string, string> = {
  // ── en-swsh1 그룹(S1W 소드 + S1H 실드) ──
  // 아이템/도구
  "クイックボール": "Quick Ball",
  "メタルソーサー": "Metal Saucer",
  "オボンのみ": "Sitrus Berry",
  "げんきのハチマキ": "Vitality Band",
  "しあわせタマゴ": "Lucky Egg",
  "しんかのおこう": "Evolution Incense",
  "すごいきずぐすり": "Hyper Potion",
  "ふつうのつりざお": "Ordinary Rod",
  "大きなおまもり": "Big Charm",
  "おおきなおまもり": "Big Charm",
  "ふうせん": "Air Balloon",
  "エアーバルーン": "Air Balloon",
  "ラムのみ": "Lum Berry",
  "ふしぎなアメ": "Rare Candy",
  "ロトムじてんしゃ": "Rotom Bike",
  // 서포트(인물)
  "エール団のしたっぱ": "Team Yell Grunt",
  "マリィ": "Marnie",
  "ビート": "Bede",
  "博士の研究": "Professor's Research (Professor Magnolia)", // SWSH base = Magnolia (이후 세트 다르면 분기)

  // ── en-swsh2 그룹(S2 반역크래시 + S1a VMAX Rising) ──
  // 아이템/도구/스타디움
  "回収ネット": "Scoop Up Net",
  "ツールスクラッパー": "Tool Scrapper",
  "のろいのスコップ": "Cursed Shovel",
  "きんのたま": "Nugget",
  "たっぷりバケツ": "Capacious Bucket",
  "燃えるスカーフ": "Burning Scarf",
  "ガラル鉱山": "Galar Mine",
  "ターフスタジアム": "Turffield Stadium",
  "トレーニングコート": "Training Court",
  // 서포트(인물)
  "オリーヴ": "Oleana",
  "ボスの指令": "Boss's Orders",
  "ダンペイ": "Dan",
  "ソニア": "Sonia",
  "フウロ": "Skyla",
  "ヤロー": "Milo",

  // ── en-swsh3 그룹(S3 무한존 + S2a 폭염워커) ──
  // 아이템/도구/스타디움
  "そっくりベル": "Familiar Bell",
  "ボロのパソコン": "Old PC",
  "ターボパッチ": "Turbo Patch",
  "おうえんYホーン": "Yell Horn",
  "めずらしい化石": "Rare Fossil",
  "タフネスマント": "Cape of Toughness",
  "もくもくスモーク": "Billowing Smoke",
  "ビッグパラソル": "Big Parasol",
  "ルミナスメイズの森": "Glimwood Tangle",
  "スパイクタウン": "Spikemuth",
  "ローズタワー": "Rose Tower",
  // 서포트(인물)
  "カブ": "Kabu",
  "ポケモンブリーダーの育成": "Pokémon Breeder's Nurturing",
  "ネズ": "Piers",
  "ローズ": "Rose",
  "とりつかい": "Bird Keeper",

  // ── en-swsh4 그룹(S4 앙천의볼테커 + S3a 전설의고동) ──
  // 아이템/도구/스타디움
  "メモリーカプセル": "Memory Capsule",
  "ドローンロトム": "Drone Rotom",
  "望遠スコープ": "Telescopic Sight",
  "英雄のメダル": "Hero's Medal",
  "ゴツゴツメット": "Rocky Helmet",
  "モーモーチーズ": "Moomoo Cheese",
  "ポケモンキャッチャー": "Pokémon Catcher",
  "キルクス温泉": "Circhester Bath",
  "シュートスタジアム": "Wyndon Stadium",
  // 서포트(인물)
  "サイトウ": "Bea",
  "ルリナ": "Nessa",
  "ダンデ": "Leon",
  "リーグスタッフ": "League Staff",
  "おとなのおねえさん": "Beauty",
  "オニオン": "Allister",
  "ポプラ": "Opal",

  // ── en-swsh5 그룹(S5I 일격마스터 + S5R 연격마스터) ──
  // 아이템/도구/스타디움
  "あくの塔": "Tower of Darkness",
  "みずの塔": "Tower of Waters",
  "あなぬけのヒモ": "Escape Rope",
  "いちげきの巻物 怒りの巻": "Single Strike Scroll of Scorn",
  "れんげきの巻物 渦の巻": "Rapid Strike Scroll of Swirls",
  "うねりの扇": "Fan of Waves",
  "エネルギーリサイクル": "Energy Recycler",
  "キャンプセット": "Camping Gear",
  "ツールジャマー": "Tool Jammer",
  "レベルボール": "Level Ball",
  "学習装置": "Exp. Share",
  "活力の壺": "Urn of Vitality",
  // 서포트(인물)
  "コルニの気合い": "Korrina's Focus",
  "シバ": "Bruno",
  "フヨウ": "Phoebe",
  "モミ": "Cheryl",
  "マスタード いちげきのかた": "Single Strike Style Mustard",
  "マスタード れんげきのかた": "Rapid Strike Style Mustard",

  // ── en-swsh6 그룹(S6H 백은의랜스 + S6K 칠흑의가이스트 + S5a 쌍벽) ──
  // 아이템/도구/스타디움
  "おむかえちょうちん": "Welcoming Lantern",
  "ガラルのむねあて": "Galarian Chestplate",
  "ダイ木の丘": "Dyna Tree Hill",
  "サバイバルセット": "Expedition Uniform",
  "耐火グローブ": "Fire-Resistant Gloves",
  "ブレイクグローブ": "Crushing Gloves",
  "頂への雪道": "Path to the Peak",
  "霧の水晶": "Fog Crystal",
  "れんげきの巻物 天の巻": "Rapid Strike Scroll of the Skies",
  "いちげきの巻物 貫通の巻": "Single Strike Scroll of Piercing",
  "いにしえの墓地": "Old Cemetery",
  "やまびこホーン": "Echoing Horn",
  "いかついメット": "Rugged Helmet",
  "草取りグローブ": "Weeding Gloves",
  "正義のグローブ": "Justified Gloves",
  // 서포트(인물)
  "カリンの信念": "Karen's Conviction",
  "クララ": "Klara",
  "セイボリー": "Avery",
  "トウキ": "Brawly",
  "ズミ": "Siebold",
  "アスナ": "Flannery",
  "メロン": "Melony",
  "ドクター": "Doctor",
  "ピオニー": "Peony",
  "カトレア": "Caitlin",
  "キクコ": "Agatha",
  "シャクヤ": "Peonia",

  // ── en-swsh7 그룹(S7R 창공스트림 + S7D 마천퍼펙트 + S6a 이브이히어로) ──
  // 아이템/도구/스타디움
  "すりかえカップ": "Switching Cups",
  "レスキューキャリー": "Rescue Carrier",
  "穴掘りグローブ": "Digging Gloves",
  "フルフェイスガード": "Full Face Guard",
  "結晶の洞窟": "Crystal Cave",
  "当たりつきアイス": "Lucky Ice Pop",
  "トイキャッチャー": "Toy Catcher",
  "ゴムのグローブ": "Rubber Gloves",
  "れいかいのお面": "Spirit Mask",
  "嵐の山脈": "Stormy Mountains",
  "いちげきの巻物 牙竜の巻": "Single Strike Scroll of the Fanged Dragon",
  "れんげきの巻物 飛竜の巻": "Rapid Strike Scroll of the Flying Dragon",
  "ファッションモール": "Shopping Center",
  "ぐんぐんシェイク": "Boost Shake",
  "ドリームボール": "Dream Ball",
  "エレメンタルバッジ": "Elemental Badge",
  "スノーリーフバッジ": "Snow Leaf Badge",
  "月と太陽のバッジ": "Moon & Sun Badge",
  "リボンバッジ": "Ribbon Badge",
  // 서포트(인물)
  "アロマなおねえさん": "Aroma Lady",
  "マクワ": "Gordie",
  "キバナ": "Raihan",
  "モノマネむすめ": "Copycat",
  "ヒガナの決意": "Zinnia's Resolve",

  // ── en-swsh8 그룹(S8 퓨전아츠) ──
  // 아이템/도구/스타디움
  "クロスシーバー": "Crossceiver",
  "クロススイッチャー": "Cross Switcher",
  "バトルVIPパス": "Battle VIP Pass",
  "パワータブレット": "Power Tablet",
  "スポンジグローブ": "Spongy Gloves",
  "なごりの大鈴": "Farewell Bell",
  "スケーターズパーク": "Skaters' Park",
  // 서포트(인물)
  "カゲツ": "Sidney",
  "カミツレのきらめき": "Elesa's Sparkle",
  "ダンサー": "Dancer",
  "ポッドとデントとコーン": "Chili & Cilan & Cress",
  "デント&ポッド&コーン": "Chili & Cilan & Cress",

  // ── en-swsh9 그룹(S9 스타버스 / Brilliant Stars) ──
  // 아이템/도구/스타디움
  "おいしいみずセット": "Fresh Water Set",
  "ハイパーボール": "Ultra Ball",
  "こだわりベルト": "Choice Belt",
  "なべメット": "Pot Helmet",
  "崩れたスタジアム": "Collapsed Stadium",
  "マグマの滝壺": "Magma Basin",
  // 서포트(인물)
  "キャンプファイヤー": "Kindler",
  "シロナの覇気": "Cynthia's Ambition",
  "チェレンの気くばり": "Cheren's Care",
  "ハマナのバックアップ": "Roseanne's Backup",
  "博士の研究（ナナカマド博士）": "Professor's Research", // ナナカマド=Rowan
  "ボスの指令（アカギ）": "Boss's Orders", // アカギ=Cyrus

  // ── 검증캠페인 사전보강(2026-06-05, 후보대조 검증) ──
  "ポケモンいれかえ": "Switch",
  "ナタネの活気": "Gardenia's Vigor",
  "セキ": "Adaman",
  "ザクロ": "Grant",
  "カイ": "Irida",
  "アクロマの実験": "Colress's Experiment",
  "おじょうさま": "Lady",
  "なぞの化石": "Unidentified Fossil",
  "サナ": "Shauna",
  "スクールボーイ": "Schoolboy",
  "スクールガール": "Schoolgirl",
  "大口の沼": "Gapejaw Bog",
  "トレッキングシューズ": "Trekking Shoes",
  "シンオウ神殿": "Temple of Sinnoh",
  "スズナ": "Candice",
  "さぎょういん": "Worker",
  "ジンダイ": "Brandon",
  "ワタル": "Lance",
  "ロストスイーパー": "Lost Vacuum",
  "メリッサ": "Fantina",
  "ネジキ": "Thorton",
  "ボールガイ": "Ball Guy",
  "スーパーボール": "Great Ball",
  "ヒスイのヘビーボール": "Hisuian Heavy Ball",
  "エネくじ": "Energy Loto",
  "葉隠れポンチョ": "Leafy Camo Poncho",
  "ツツジ": "Roxanne",
  "ヒスイの仲間たち": "Friends in Hisui",
  "ミラージュゲート": "Mirage Gate",
  "シンオウの仲間たち": "Friends in Sinnoh",
  "妖しいカンヅメ": "Suspicious Food Tin",
  "エール団のおうえんタオル": "Team Yell Towel",
  "くちたけん": "Rusted Sword",
  "くちたたて": "Rusted Shield",
  "ウカッツ": "Cara Liss",
  "ポケモンごっこ": "Poké Kid",
  "ジムトレーナー": "Gym Trainer",
  "なきわめくホルン": "Wailing Horn",
  "いれかえカート": "Switch Cart",
  "フェザーボール": "Feather Ball",
  "ばつぐんグラス": "Choice Belt",
  "クワッドストーン": "Quad Stone",
  "森の封印石": "Forest Seal Stone",
  "大地の封印石": "Earthen Seal Stone",
  "未開の祭壇": "Primordial Altar",
  "ダークパッチ": "Dark Patch",
  "ウォロ": "Volo",
  "空の封印石": "Sky Seal Stone",
  "ガッツのつるはし": "Gutsy Pickaxe",
  "ダメージポンプ": "Damage Pump",
  "コトブキムラ": "Jubilife Village",
  "ツールボックス": "Tool Box",
  "ロストシティ": "Lost City",
  "パニックマスク": "Panic Mask",
};
